name: GitHub CICD

on:
  push:
    branches:
      - main  # You can change 'main' to your primary branch name if it's different.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Replace 'x' with the desired Python version (e.g., 3.6, 3.7, 3.8).

      - name: Install dependencies
        run: |
          pip install black pytest
          pip install -r requirements.txt

      - name: Install dependencies
        run: pip install black pytest

      - name: Run Black formatter
        run: black .

      - name: Run Pytest
        run: pytest tests/  # This will run pytest on all files in the 'tests/' directory.
